---------------------1-----------------
CREATE OR REPLACE PROCEDURE GET_TEACHERS(CODE TEACHER.PULPIT%TYPE)
IS
CURSOR CUR_TEACH
IS SELECT TEACHER,TEACHER_NAME,GENDER,PULPIT,BIRTHDAY,SALARY FROM TEACHER;
CC_SUB TEACHER%ROWTYPE;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
IF CC_SUB.PULPIT=CODE THEN DBMS_OUTPUT.PUT_LINE(CC_SUB.TEACHER||' '||CC_SUB.TEACHER_NAME); END IF;
FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
END GET_TEACHERS;

BEGIN
GET_TEACHERS('ISiT');
END;
------------------------2------------------
CREATE OR REPLACE FUNCTION GET_NUM_TEACHERS (CODE TEACHER.PULPIT%TYPE)
RETURN NUMBER IS
CURSOR CUR_TEACH
IS SELECT TEACHER,TEACHER_NAME,GENDER,PULPIT,BIRTHDAY,SALARY FROM TEACHER;
CC_SUB TEACHER%ROWTYPE;
COUNTS NUMBER:=0;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
IF CC_SUB.PULPIT=CODE THEN COUNTS:=COUNTS+1;  END IF;
FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
RETURN COUNTS;
END GET_NUM_TEACHERS ;

DECLARE
X NUMBER;
BEGIN
X:=GET_NUM_TEACHERS ('ISiT');
DBMS_OUTPUT.PUT_LINE('COUNT='||X);
END; 
---------------------3--------------------
CREATE OR REPLACE PROCEDURE GET_SUBJECT(CODE SUBJECT.PULPIT%TYPE)
IS
CURSOR CUR_TEACH
IS SELECT SUBJECT,SUBJECT_NAME,PULPIT FROM SUBJECT;
CC_SUB SUBJECT%ROWTYPE;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
IF CC_SUB.PULPIT=CODE THEN DBMS_OUTPUT.PUT_LINE(CC_SUB.SUBJECT_NAME); END IF;
FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
END GET_SUBJECT;

BEGIN
GET_SUBJECT('ISiT');
END;
--------------------4----------------------
SELECT * FROM subject;

CREATE OR REPLACE FUNCTION GET_NUM_SUBJECTS (CODE SUBJECT.PULPIT%TYPE)
RETURN NUMBER IS
CURSOR CUR_TEACH
IS SELECT SUBJECT,SUBJECT_NAME,PULPIT FROM SUBJECT;
CC_SUB SUBJECT%ROWTYPE;
COUNTS NUMBER:=0;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
IF CC_SUB.PULPIT=CODE THEN COUNTS:=COUNTS+1;  END IF;
FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
RETURN COUNTS;
END  GET_NUM_SUBJECTS ;

DECLARE
X NUMBER;
BEGIN
X:=GET_NUM_SUBJECTS('ISiT'); 
DBMS_OUTPUT.PUT_LINE('COUNT OF SUBJECTS = '||X);
END; 

------------------5--------------
CREATE OR REPLACE PACKAGE PACK AS
PROCEDURE  GET_TEACHERS(CODE TEACHER.PULPIT%TYPE);
PROCEDURE  GET_SUBJECT(CODE SUBJECT.PULPIT%TYPE);
FUNCTION GET_NUM_TEACHERS (CODE TEACHER.PULPIT%TYPE) RETURN NUMBER;
FUNCTION GET_NUM_SUBJECTS (CODE SUBJECT.PULPIT%TYPE) RETURN NUMBER;
END PACK;


CREATE OR REPLACE PACKAGE BODY PACK IS
PROCEDURE GET_TEACHERS(CODE TEACHER.PULPIT%TYPE)
IS
CURSOR CUR_TEACH
IS SELECT TEACHER,TEACHER_NAME,GENDER,PULPIT,BIRTHDAY,SALARY FROM TEACHER;
CC_SUB TEACHER%ROWTYPE;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
IF CC_SUB.PULPIT=CODE THEN DBMS_OUTPUT.PUT_LINE(CC_SUB.TEACHER||' '||CC_SUB.TEACHER_NAME); END IF;
FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
END GET_TEACHERS;

PROCEDURE GET_SUBJECT(CODE SUBJECT.PULPIT%TYPE)
IS
CURSOR CUR_TEACH
IS SELECT SUBJECT,SUBJECT_NAME,PULPIT FROM SUBJECT;
CC_SUB SUBJECT%ROWTYPE;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
IF CC_SUB.PULPIT=CODE THEN DBMS_OUTPUT.PUT_LINE(CC_SUB.SUBJECT_NAME); END IF;
FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
END GET_SUBJECT;

FUNCTION GET_NUM_TEACHERS (CODE TEACHER.PULPIT%TYPE)
RETURN NUMBER IS
CURSOR CUR_TEACH
IS SELECT TEACHER,TEACHER_NAME,GENDER,PULPIT,BIRTHDAY,SALARY FROM TEACHER;
CC_SUB TEACHER%ROWTYPE;
COUNTS NUMBER:=0;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
IF CC_SUB.PULPIT=CODE THEN COUNTS:=COUNTS+1;  END IF;
FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
RETURN COUNTS;
END GET_NUM_TEACHERS ;

FUNCTION GET_NUM_SUBJECTS (CODE SUBJECT.PULPIT%TYPE)
RETURN NUMBER IS
CURSOR CUR_TEACH
IS SELECT SUBJECT,SUBJECT_NAME,PULPIT FROM SUBJECT;
CC_SUB SUBJECT%ROWTYPE;
COUNTS NUMBER:=0;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
IF CC_SUB.PULPIT=CODE THEN COUNTS:=COUNTS+1;  END IF;
FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
RETURN COUNTS;
END  GET_NUM_SUBJECTS ;
END;

BEGIN
 pack.get_teachers('ISiT');
 dbms_output.put_line('COUNT :' || pack.get_num_teachers('ISiT'));
 
 pack.get_subject('ISiT');
 dbms_output.put_line('COUNT :' || pack.get_num_subjects('ISiT'));
END;