CREATE OR REPLACE PROCEDURE GET_TEACHERS(CODE TEACHERR.PULPIT%TYPE)
IS
CURSOR CUR_TEACH
IS SELECT TEACHER,TEACHER_NAME,PULPIT FROM TEACHERR;
CC_SUB TEACHERR%ROWTYPE;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
IF CC_SUB.PULPIT=CODE THEN DBMS_OUTPUT.PUT_LINE(CC_SUB.TEACHER||' '||CC_SUB.TEACHER_NAME); END IF;
FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
END GET_TEACHERS;

BEGIN
GET_TEACHERS('ISiT');
END;
------------------------2------------------
CREATE OR REPLACE FUNCTION GET_NUM_TEACHERS (CODE TEACHERR.PULPIT%TYPE)
RETURN NUMBER IS
CURSOR CUR_TEACH
IS SELECT TEACHER,TEACHER_NAME,PULPIT FROM TEACHERR;
CC_SUB TEACHERR%ROWTYPE;
COUNTS NUMBER:=0;
BEGIN
OPEN CUR_TEACH;
FETCH CUR_TEACH INTO CC_SUB;
WHILE CUR_TEACH%FOUND
LOOP
IF CC_SUB.PULPIT=CODE THEN COUNTS:=COUNTS+1;  END IF;
FETCH CUR_TEACH INTO CC_SUB;
END LOOP;
CLOSE CUR_TEACH;
RETURN COUNTS;
END GET_NUM_TEACHERS ;

DECLARE
X NUMBER;
BEGIN
X:=GET_NUM_TEACHERS ('ISiT');
DBMS_OUTPUT.PUT_LINE('COUNT='||X);
END; 